const fs = require('fs');

const questions = [
  {
    id: "bgk-001",
    section: "bankacilik-genel-kultur",
    topic: "Ziraat Bankası Tarihçesi ve Kuruluşu",
    subtopic: "Memleket Sandıkları",
    difficulty: "easy",
    questionType: "kavram-bilgisi",
    questionText: "Ziraat Bankası'nın tarihsel kökeni kabul edilen ve 1863 yılında Niş Valisi Mithat Paşa tarafından çiftçilere uygun koşullarda kredi sağlamak amacıyla kurulan ilk mali teşkilat aşağıdakilerden hangisidir?",
    options: [
      "Emniyet Sandığı",
      "Memleket Sandıkları",
      "Dersaadet Tahvilat Borsası",
      "Osmanlı İtibar-ı Milli Bankası",
      "Menafi Sandıkları"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Ziraat Bankası'nın temeli, 1863 yılında Mithat Paşa tarafından Pirot kasabasında kurulan 'Memleket Sandıkları'dır. 1883'te Menafi Sandıkları'na, 15 Ağustos 1888'de ise resmi nizamnamesiyle modern Ziraat Bankası'na dönüştürülmüştür.",
    estimatedTimeSeconds: 45,
    tags: ["ziraat-bankasi", "mithat-pasa", "tarihce", "memleket-sandiklari"],
    sourceName: "Ziraat Bankası Resmi Tarihçe",
    sourceUrl: "https://www.ziraatbank.com.tr/tr/bankamiz/hakkimizda/tarihce",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-002",
    section: "bankacilik-genel-kultur",
    topic: "Ziraat Bankası Ürün ve Hizmetleri",
    subtopic: "Tarım Kartı",
    difficulty: "easy",
    questionType: "bankacilik-terimi",
    questionText: "Ziraat Bankası'nın çiftçi ve üreticilere mazot, gübre, tohum ve yem gibi tarımsal girdi alımlarında faiz sübvansiyonlu veya vadeli harcama imkanı sunan tescilli bankacılık kartı aşağıdakilerden hangisidir?",
    options: [
      "Bankkart Genç",
      "Başakkart (Bankkart Başak)",
      "Ziraat Maximum",
      "Troy Esnaf Kart",
      "Ziraat Hasat Kart"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Ziraat Bankası üreticilere tarımsal işletme giderlerini finanse etmeleri amacıyla Bankkart Başak (Başakkart) sunmaktadır. Bu kartla anlaşmalı üye işyerlerinden sübvansiyonlu tarımsal girdi temin edilebilir.",
    estimatedTimeSeconds: 40,
    tags: ["ziraat-bankasi", "basakkart", "tarim-kredisi", "kartli-odeme"],
    sourceName: "Ziraat Bankası Tarımsal Bankacılık",
    sourceUrl: "https://www.ziraatbank.com.tr/tr/tarimsal/bankkart-basak",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-003",
    section: "bankacilik-genel-kultur",
    topic: "TCMB ve Para Politikası",
    subtopic: "Temel Amaç ve Araçlar",
    difficulty: "medium",
    questionType: "kurum-gorevi",
    questionText: "1211 sayılı Türkiye Cumhuriyet Merkez Bankası (TCMB) Kanunu'na göre, Merkez Bankası'nın temel ve birincil amacı aşağıdakilerden hangisidir?",
    options: [
      "Bütçe açığını kapatmak için kamuya borç vermek",
      "Fiyat istikrarını sağlamak",
      "Bireysel kredi faiz oranlarının üst sınırını tek başına belirlemek",
      "Döviz kurlarını belirli bir bantta sabit tutmak",
      "Ticari bankaların karlılık hedeflerini denetlemek"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "1211 sayılı TCMB Kanunu'nun 4. maddesi gereğince Bankanın temel amacı 'fiyat istikrarını sağlamaktır'. Banka, fiyat istikrarı hedefiyle çelişmemek kaydıyla hükümetin büyüme ve istihdam politikalarını destekler.",
    estimatedTimeSeconds: 45,
    tags: ["tcmb", "fiyat-istikrari", "para-politikasi"],
    sourceName: "TCMB Resmi Mevzuatı (1211 Sayılı Kanun)",
    sourceUrl: "https://www.tcmb.gov.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-004",
    section: "bankacilik-genel-kultur",
    topic: "TCMB ve Para Politikası",
    subtopic: "Politika Faizi",
    difficulty: "medium",
    questionType: "kavram-bilgisi",
    questionText: "TCMB Para Politikası Kurulu'nun (PPK) faiz kararlarında referans olarak belirlediği temel 'Politika Faizi' aşağıdakilerden hangisidir?",
    options: [
      "Gecelik Borçlanma Faizi (O/N)",
      "Geç Likidite Penceresi (GLP) Faizi",
      "Bir Hafta Vadeli Repo İhale Faiz Oranı",
      "Bankalararası Para Piyasası Ağırlıklı Ortalama Faizi",
      "Reeskont Kredi Faiz Oranı"
    ],
    correctAnswer: 2,
    answerIndex: 2,
    explanation: "TCMB'nin temel politika faizi 'Bir hafta vadeli repo ihale faiz oranı'dır. Merkez Bankası piyasa yapıcı bankalara likiditeyi temel olarak bu oran üzerinden haftalık repo ihaleleriyle sağlar.",
    estimatedTimeSeconds: 50,
    tags: ["tcmb", "politika-faizi", "repo"],
    sourceName: "TCMB Para Politikası Araçları",
    sourceUrl: "https://www.tcmb.gov.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-005",
    section: "bankacilik-genel-kultur",
    topic: "Bankacılık Düzenleme ve Denetleme",
    subtopic: "BDDK ve Rasyolar",
    difficulty: "medium",
    questionType: "kurum-gorevi",
    questionText: "5411 sayılı Bankacılık Kanunu çerçevesinde Türkiye'de bankaların faaliyet izinlerini veren, rasyolarını denetleyen ve mevzuata uyumunu gözetleyen bağımsız idari otorite hangisidir?",
    options: [
      "Sermaye Piyasası Kurulu (SPK)",
      "Bankacılık Düzenleme ve Denetleme Kurumu (BDDK)",
      "Tasarruf Mevduatı Sigorta Fonu (TMSF)",
      "Türkiye Bankalar Birliği (TBB)",
      "Maliye Bakanlığı Finansal Piyasalar Genel Müdürlüğü"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "BDDK (Bankacılık Düzenleme ve Denetleme Kurumu), bankacılık sektörünün güven ve istikrar içinde çalışmasını sağlamak, mudilerin haklarını korumak ve riskleri denetlemekle görevli bağımsız düzenleyici üst kuruldur.",
    estimatedTimeSeconds: 40,
    tags: ["bddk", "denetim", "bankacilik-kanunu"],
    sourceName: "BDDK Kurumsal Portalı",
    sourceUrl: "https://www.bddk.org.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-006",
    section: "bankacilik-genel-kultur",
    topic: "Mevduat ve Kredi Kavramları",
    subtopic: "TMSF Mevduat Sigortası",
    difficulty: "medium",
    questionType: "bankacilik-terimi",
    questionText: "Türkiye'de faaliyet gösteren bir mevduat bankasında gerçek kişilerin ticari olmayan tasarruf mevduatlarını yasal limitler dahilinde garanti ve sigorta altına alan resmi kurum hangisidir?",
    options: [
      "Hazine ve Maliye Bakanlığı",
      "Tasarruf Mevduatı Sigorta Fonu (TMSF)",
      "Merkez Bankası Takas ve Saklama Anonim Şirketi",
      "Sigortacılık ve Özel Emeklilik Düzenleme Kurumu (SEDDK)",
      "Türkiye Bankalar Birliği Risk Merkezi"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "TMSF (Tasarruf Mevduatı Sigorta Fonu), bankalara yatırılan bireysel tasarruf mevduatlarını belirlenen yasal sigorta tutarına kadar devlet garantisi altında tazmin etmekle yetkilidir.",
    estimatedTimeSeconds: 45,
    tags: ["tmsf", "mevduat-sigortasi", "mudiler"],
    sourceName: "TMSF Mevzuat ve Sigorta Kapsamı",
    sourceUrl: "https://www.tmsf.org.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-007",
    section: "bankacilik-genel-kultur",
    topic: "Bankacılık Risk Yönetimi",
    subtopic: "Kredi Riski ve NPL",
    difficulty: "hard",
    questionType: "bankacilik-terimi",
    questionText: "Bankacılık terminolojisinde borçlunun kredi anapara veya faiz ödemelerini vadesinde yerine getirememesi sonucu 90 günden fazla gecikmeye giren ve takibe aktarılan alacaklara ne ad verilir?",
    options: [
      "Kaldıraçlı Alacaklar",
      "Takipteki Krediler (Non-Performing Loans - NPL)",
      "Arbitraj Kredileri",
      "İskontolu Senetler",
      "Sendikasyon Kredileri"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Vadesi üzerinden 90 gün geçen ve geri ödenmesi şüpheli hale gelen krediler 'Takipteki Alacaklar' (NPL - Non-Performing Loans) kategorisine aktarılır ve bankalar bunlar için karşılık (provision) ayırmak zorundadır.",
    estimatedTimeSeconds: 50,
    tags: ["kredi-riski", "npl", "takipteki-alacaklar", "risk-yonetimi"],
    sourceName: "BDDK Kredilerin Sınıflandırılması Yönetmeliği",
    sourceUrl: "https://www.bddk.org.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-008",
    section: "bankacilik-genel-kultur",
    topic: "Bankacılık Risk Yönetimi",
    subtopic: "Likidite ve Sermaye Yeterliliği",
    difficulty: "hard",
    questionType: "kavram-bilgisi",
    questionText: "Basel standartları ve BDDK düzenlemeleri uyarınca bir bankanın sahip olduğu özkaynakların, maruz kaldığı risk ağırlıklı varlıklara (kredi, piyasa ve operasyonel risk) oranlanmasıyla hesaplanan göstergeye ne ad verilir?",
    options: [
      "Likidite Karşılama Oranı (LCR)",
      "Net Faiz Marjı (NIM)",
      "Sermaye Yeterlilik Rasyosu (SYR / CAR)",
      "Fiyat/Kazanç Oranı (F/K)",
      "Takipteki Alacak Karşılık Oranı"
    ],
    correctAnswer: 2,
    answerIndex: 2,
    explanation: "Sermaye Yeterlilik Rasyosu (SYR - Capital Adequacy Ratio), bir bankanın olası şoklara ve zararlara karşı yeterli özkaynağa sahip olup olmadığını ölçer. Yasal alt sınır %8, BDDK hedef rasyosu ise genellikle %12'dir.",
    estimatedTimeSeconds: 55,
    tags: ["syr", "basel", "sermaye-yeterliligi", "risk"],
    sourceName: "BDDK Sermaye Yeterliliği Yönetmeliği",
    sourceUrl: "https://www.bddk.org.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-009",
    section: "bankacilik-genel-kultur",
    topic: "Bireysel ve Ticari Bankacılık",
    subtopic: "Kredi Türleri",
    difficulty: "medium",
    questionType: "senaryo-yorumu",
    questionText: "Bir şirketin banka ile belirlediği bir limit dahilinde, ihtiyaç duydukça para çekebildiği ve faizin yalnızca kullanılan gün ve tutar üzerinden hesaplandığı esnek ticari kredi türü hangisidir?",
    options: [
      "Taksitli Ticari Kredi",
      "Rotatif (Borçlu Cari Hesap) Kredi",
      "Akreditif Kredisi",
      "Prefinansman Kredisi",
      "Forfaiting Kredisi"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Rotatif kredi (Borçlu Cari Hesap - BCH), firmanın limit dahilinde dilediğinde para çekip dilediğinde geri yatırabildiği, faizin sadece paranın fiilen kullanıldığı gün üzerinden işletildiği kredidir.",
    estimatedTimeSeconds: 50,
    tags: ["rotatif-kredi", "ticari-bankacilik", "bch"],
    sourceName: "TBB Bankacılık Terimleri Kılavuzu",
    sourceUrl: "https://www.tbb.org.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-010",
    section: "bankacilik-genel-kultur",
    topic: "Ödeme Sistemleri ve Dijital Bankacılık",
    subtopic: "FAST Sistemi",
    difficulty: "easy",
    questionType: "kavram-bilgisi",
    questionText: "TCMB tarafından işletilen, farklı bankalardaki hesaplar arasında 7/24 anlık para transferi sağlayan ve Kolay Adresleme (telefon, T.C. kimlik, e-posta) sistemini destekleyen altyapı hangisidir?",
    options: [
      "EFT (Elektronik Fon Transferi)",
      "FAST (Fonların Anlık ve Sürekli Transferi)",
      "SWIFT",
      "Havale Sistemi",
      "BKM Express"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "FAST (Fonların Anlık ve Sürekli Transferi), TCMB tarafından hayata geçirilen, haftanın 7 günü 24 saati birkaç saniye içinde farklı bankalar arası para transferi gerçekleştiren modern perakende ödeme sistemidir.",
    estimatedTimeSeconds: 40,
    tags: ["fast", "odeme-sistemleri", "tcmb", "dijital-bankacilik"],
    sourceName: "TCMB FAST Bilgilendirme Sayfası",
    sourceUrl: "https://www.tcmb.gov.tr/wps/wcm/connect/tr/tcmb+tr/main+menu/temel+faaliyetler/odeme+sistemleri/fast",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-011",
    section: "bankacilik-genel-kultur",
    topic: "Bilanço ve Finansal Tablolar",
    subtopic: "Banka Bilançosu",
    difficulty: "medium",
    questionType: "kavram-bilgisi",
    questionText: "Bir ticari bankanın bilançosunda müşterilerden toplanan mevduatlar ve bankanın müşterilere kullandırdığı krediler sırasıyla hangi bilanço kalemlerinde yer alır?",
    options: [
      "Mevduat: Aktif | Krediler: Pasif",
      "Mevduat: Pasif | Krediler: Aktif",
      "Her ikisi de Aktif kalemdir",
      "Her ikisi de Pasif kalemdir",
      "Mevduat: Gelir Tablosu | Krediler: Nazım Hesaplar"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Bankalar için müşterilerin yatırdığı mevduat bir borç/yükümlülüktür (Pasif). Kullandırılan krediler ise bankanın alacağı olan finansal varlıklardır (Aktif). Bu yönüyle banka bilançosu reel sektör bilançosunun tersi mantıkla çalışır.",
    estimatedTimeSeconds: 50,
    tags: ["bilanco", "aktif-pasif", "mevduat", "krediler"],
    sourceName: "Finansal Muhasebe İlkeleri",
    sourceUrl: "https://www.bddk.org.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-012",
    section: "bankacilik-genel-kultur",
    topic: "Enflasyon ve Para Politikası",
    subtopic: "Enflasyon Dinamikleri",
    difficulty: "medium",
    questionType: "kavram-bilgisi",
    questionText: "Petrol, elektrik ve döviz kuru gibi üretim girdilerinin maliyetlerinin artması sebebiyle ürün ve hizmet fiyatlarının genel seviyesinin yükselmesine ne ad verilir?",
    options: [
      "Talep Enflasyonu",
      "Maliyet (Arz) Enflasyonu",
      "Gizli Enflasyon",
      "Kronik Enflasyon",
      "Çekirdek Enflasyon"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Üretim maliyetlerinin (hammadde, enerji, işçilik, kur artışı) yükselmesi nedeniyle toplam arz eğrisinin sola kayması ve fiyatların artması 'Maliyet (veya İtme) Enflasyonu' olarak adlandırılır.",
    estimatedTimeSeconds: 45,
    tags: ["enflasyon", "maliyet-enflasyonu", "ekonomi"],
    sourceName: "TCMB Ekonomi Bülteni",
    sourceUrl: "https://www.tcmb.gov.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-013",
    section: "bankacilik-genel-kultur",
    topic: "Tarım Bankacılığı ve Finansman",
    subtopic: "Sübvansiyonlu Krediler",
    difficulty: "medium",
    questionType: "senaryo-yorumu",
    questionText: "Ziraat Bankası'nın üreticilere kullandırdığı Hazine faiz destekli (sübvansiyonlu) tarımsal kredilerde faiz indirim oranları hangi resmi kriterlere göre farklılaşır?",
    options: [
      "Yalnızca borçlunun yaşına göre",
      "Yatırımın konusu (damla sulama, genç çiftçi, kadın girişimci, sözleşmeli üretim) ve öncelikli ürün grubuna göre",
      "Tarımsal arazinin tapu kadastro harç bedeline göre",
      "Yalnızca şirketin halka arz durumuna göre",
      "Sadece üreticinin kredi kartı harcama geçmişine göre"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Cumhurbaşkanlığı Kararı uyarınca Ziraat Bankası tarımsal kredilerinde; basınçlı sulama sistemleri, genç/kadın çiftçi, stratejik bitkisel üretim ve sözleşmeli tarım gibi hedeflere göre %20'den %100'e (tamamen sıfır faiz) varan indirimler uygulanır.",
    estimatedTimeSeconds: 55,
    tags: ["tarim-bankaciligi", "subvansiyonlu-kredi", "hazine-destegi", "ziraat"],
    sourceName: "Resmi Gazete Tarımsal Kredi Kararnameleri",
    sourceUrl: "https://www.resmigazete.gov.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-014",
    section: "bankacilik-genel-kultur",
    topic: "Fintech ve Dijital Dönüşüm",
    subtopic: "Açık Bankacılık ve API",
    difficulty: "medium",
    questionType: "kavram-bilgisi",
    questionText: "Bankaların müşteri açık rızasıyla hesap bilgisi ve ödeme başlatma servislerini lisanslı fintech kuruluşlarına standart arayüzlerle sunduğu düzenleme (PSD2 uyumlu) hangisidir?",
    options: [
      "Açık Bankacılık (Open Banking / GEÇS)",
      "Kapalı Devre Sanal POS",
      "Gölge Bankacılık (Shadow Banking)",
      "Kripto Varlık Soğuk Depolama",
      "Mikro Finans Sistemi"
    ],
    correctAnswer: 0,
    answerIndex: 0,
    explanation: "Açık Bankacılık, TCMB 6493 sayılı kanun düzenlemeleriyle bankaların hesap bilgisi sağlama (HBS) ve ödeme emri başlatma (ÖEB) servislerini API'lar üzerinden yetkili ödeme kuruluşlarına açtığı sistemdir.",
    estimatedTimeSeconds: 50,
    tags: ["fintech", "acik-bankacilik", "api", "psd2"],
    sourceName: "TCMB Açık Bankacılık Yönetmeliği",
    sourceUrl: "https://www.tcmb.gov.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-015",
    section: "bankacilik-genel-kultur",
    topic: "Türkiye Bankacılık Sistemi",
    subtopic: "Banka Türleri",
    difficulty: "easy",
    questionType: "kavram-bilgisi",
    questionText: "5411 sayılı Bankacılık Kanunu'na göre Türkiye'de faaliyet gösteren 'Kalkınma ve Yatırım Bankaları'nın mevduat bankalarından en temel yasal farkı aşağıdakilerden hangisidir?",
    options: [
      "Kredi verememeleri",
      "Mevduat kabul edememeleri",
      "Yabancı para işlemi yapamamaları",
      "TCMB'ye tabi olmamaları",
      "Şube açamamaları"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Kalkınma ve Yatırım Bankaları mevduat (veya katılım fonu) toplayamazlar. Fon kaynaklarını özkaynaklar, tahvil ihracı ve uluslararası finans kuruluşlarından sağladıkları uzun vadeli krediler oluşturur (Örn: İller Bankası, Eximbank).",
    estimatedTimeSeconds: 45,
    tags: ["yatirim-bankaciligi", "mevduat", "banka-turleri"],
    sourceName: "5411 Sayılı Bankacılık Kanunu Madde 3",
    sourceUrl: "https://www.bddk.org.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-016",
    section: "bankacilik-genel-kultur",
    topic: "Genel Kültür ve Ekonomi Tarihi",
    subtopic: "İzmir İktisat Kongresi",
    difficulty: "medium",
    questionType: "kavram-bilgisi",
    questionText: "1923 yılında toplanan İzmir İktisat Kongresi'nde kabul edilen ve yerli üretimi, milli sermayeyi ve tasarrufu özendirmeyi amaçlayan tarihi bildiriye ne ad verilir?",
    options: [
      "Misak-ı Milli",
      "Misak-ı İktisadi",
      "Teşvik-i Sanayi",
      "Kanun-i Esasi",
      "Tekalif-i Milliye"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "İzmir İktisat Kongresi'nde 'Misak-ı İktisadi' (Ekonomi Andı) kabul edilerek genç Cumhuriyetin ekonomik bağımsızlık ilkeleri ve milli kalkınma hedefleri ilan edilmiştir.",
    estimatedTimeSeconds: 40,
    tags: ["cumhuriyet-tarihi", "misak-i-iktisadi", "izmir-iktisat-kongresi"],
    sourceName: "Atatürk Araştırma Merkezi",
    sourceUrl: "https://www.atam.gov.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-017",
    section: "bankacilik-genel-kultur",
    topic: "Türkiye Ekonomisi",
    subtopic: "Cari Denge",
    difficulty: "medium",
    questionType: "kavram-bilgisi",
    questionText: "Bir ülkenin mal ve hizmet ihracatından elde ettiği gelirlerin, mal ve hizmet ithalatına ödediği giderlerden az olması durumunda ortaya çıkan dış ekonomik açık göstergesi hangisidir?",
    options: [
      "Bütçe Açığı",
      "Cari İşlemler Açığı (Cari Açık)",
      "Reeskont Açığı",
      "Enflasyon Farkı",
      "Operasyonel Zarar"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Cari İşlemler Dengesi, bir ülkenin dış ticaret (mal), hizmetler, birincil ve ikincil gelir dengesini kapsar. Giderlerin gelirleri aşması 'Cari Açık' olarak tanımlanır.",
    estimatedTimeSeconds: 45,
    tags: ["cari-acik", "dis-ticaret", "turkiye-ekonomisi"],
    sourceName: "TCMB Ödemeler Dengesi İstatistikleri",
    sourceUrl: "https://www.tcmb.gov.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-018",
    section: "bankacilik-genel-kultur",
    topic: "Finansal Piyasalar",
    subtopic: "Sermaye Piyasası Kurulu",
    difficulty: "easy",
    questionType: "kurum-gorevi",
    questionText: "Halka arz edilen şirketlerin hisse senetleri, tahviller ve yatırım fonları gibi sermaye piyasası araçlarının ihracını ve Borsa İstanbul işlemlerini denetleyen üst kurul hangisidir?",
    options: [
      "Bankacılık Düzenleme ve Denetleme Kurumu (BDDK)",
      "Sermaye Piyasası Kurulu (SPK)",
      "Rekabet Kurumu",
      "Kamu Gözetimi Kurumu (KGK)",
      "Merkezi Finans ve İhale Birimi"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "6362 sayılı Sermaye Piyasası Kanunu uyarınca menkul kıymet piyasalarının, halka açık anonim ortaklıkların ve borsa aracı kurumlarının düzenleyicisi SPK'dır.",
    estimatedTimeSeconds: 40,
    tags: ["spk", "sermaye-piyasasi", "borsa-istanbul"],
    sourceName: "SPK Resmi Portalı",
    sourceUrl: "https://www.spk.gov.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-019",
    section: "bankacilik-genel-kultur",
    topic: "Bankacılık ve Para Teorisi",
    subtopic: "Zorunlu Karşılıklar",
    difficulty: "hard",
    questionType: "kavram-bilgisi",
    questionText: "Merkez Bankası'nın ticari bankalardan topladıkları mevduatın belirli bir oranını kendi bünyesinde bloke etmesini zorunlu kıldığı para politikası aracına ne ad verilir?",
    options: [
      "Disponibilite Oranı",
      "Zorunlu Karşılık Oranı (Munzam Karşılık)",
      "Arbitraj Marjı",
      "Kredi Değerleme Oranı (LTV)",
      "Faiz Koridoru"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Zorunlu Karşılık Oranı (Munzam Karşılık), bankaların topladıkları mevduatın kanunen Merkez Bankası'nda tutmak zorunda oldukları yüzdesidir. Bu oran artırıldığında bankaların kredi verme kapasitesi ve piyasadaki para arzı daralır.",
    estimatedTimeSeconds: 50,
    tags: ["zorunlu-karsilik", "tcmb", "para-politikasi-araclari"],
    sourceName: "TCMB Zorunlu Karşılıklar Tebliği",
    sourceUrl: "https://www.tcmb.gov.tr",
    sourceVerifiedAt: "2026-10-08"
  },
  {
    id: "bgk-020",
    section: "bankacilik-genel-kultur",
    topic: "Ziraat Finans Grubu",
    subtopic: "İştirakler ve Ekosistem",
    difficulty: "medium",
    questionType: "kavram-bilgisi",
    questionText: "Ziraat Finans Grubu bünyesinde faizsiz bankacılık ilkeleriyle hizmet vermek amacıyla 2015 yılında Türkiye'nin ilk kamu katılım bankası olarak faaliyete başlayan kurum hangisidir?",
    options: [
      "Vakıf Katılım Bankası",
      "Ziraat Katılım Bankası",
      "Türkiye Emlak Katılım Bankası",
      "Kuveyt Türk",
      "Albaraka Türk"
    ],
    correctAnswer: 1,
    answerIndex: 1,
    explanation: "Ziraat Katılım Bankası A.Ş., BDDK izinleriyle 29 Mayıs 2015 tarihinde faaliyete başlamış olup Türkiye'nin kurulan ilk kamu sermayeli katılım bankasıdır.",
    estimatedTimeSeconds: 45,
    tags: ["ziraat-katilim", "ziraat-finans-grubu", "katilim-bankaciligi"],
    sourceName: "Ziraat Katılım Resmi Portalı",
    sourceUrl: "https://www.ziraatkatilim.com.tr",
    sourceVerifiedAt: "2026-10-08"
  }
];

fs.writeFileSync('data/questions/bankacilik_genel_kultur.json', JSON.stringify(questions, null, 2), 'utf8');
console.log('bankacilik_genel_kultur.json created with 20 questions successfully.');
